import fs from 'node:fs/promises';
import path from 'node:path';
import { PresentationFile } from '@oai/artifact-tool';

const [starterArg, outputArg] = process.argv.slice(2);
if (!starterArg || !outputArg) throw new Error('Usage: node build_application_deck_full.mjs <template-starter.pptx> <output.pptx>');
const STARTER=path.resolve(starterArg), OUT=path.resolve(outputArg);
const P='#5B1A6E', P2='#7A3E8E', L='#F4EDF7', L2='#EDE3F1', INK='#25212A', MUTED='#6D6672', GRID='#D9D2DC', GREEN='#2E7D65', ORANGE='#C86B2A', RED='#A23B55', BLUE='#3569A8';
const bodyFont='等线', enFont='Arial';
const deck=await PresentationFile.importPptx(await fs.readFile(STARTER));

const slides=[
  null,null,null,null,
  {sec:'Clinical Detection and Intervention',sub:'1.1 Active observational sensing',title:'主动观察式检测：研究集群与证据边界',kind:'landscape',lead:'研究量 ≠ 临床成熟度：机器人超声形成最大集群，闭环证据仍集中在少数人体可行性研究。',items:[['机器人超声','529','人体可行性'],['内镜搜索/巡检','261','多为导航/覆盖'],['机器人 OCT','50','多为体外/原型'],['听诊与表面扫描','<30','稀疏']],foot:'计量口径：题名/摘要闭环候选快照；跨数据库去重与全文筛选仍在持续。'},
  {sec:'Clinical Detection and Intervention',sub:'1.1 Active observational sensing',title:'方向一：不确定性驱动的机器人超声',kind:'evidence',lead:'让图像质量、解剖置信度与接触状态共同决定下一次探头动作。',loop:['实时超声 + 力','切面/病灶状态','下一位姿/压力','复扫或停止'],metrics:[['甲状腺 2024','70 人问卷；13 人配对扫描','213±85 s/叶'],['颈动脉 2025','247k 专家示教','>90% 成功；最高 5.5×复现']],hardware:'7-DOF/协作臂 · 临床超声 · 六维力传感 · RGB-D/外部相机',gap:'下一步：跨体型与病变分布泛化；以“充分决策时间、漏扫、患者不适”而非单一切面成功率评价。'},
  {sec:'Clinical Detection and Intervention',sub:'1.1 Active observational sensing',title:'方向二：主动光学与内镜扫描',kind:'roadmap',lead:'价值不在固定轨迹自动化，而在诊断不确定性驱动的 next-best-view、复扫与停止。',stages:[['筛查','MSI / HSI / 宽场成像','覆盖与可疑区'],['靶向确认','OCT / Raman / DRS','边界与组织特征'],['闭环动作','新测点 / 改角度 / 改接触','置信度达标后停止']],resources:[['数据','空间配准的多模态扫描；病理或专家边界'],['硬件','机器人/主动内镜；位姿追踪；接触/距离传感'],['可验证终点','单位时间的信息增益、遗漏病灶、复扫次数、覆盖盲区']],gap:'现有工作常把“到达/覆盖”当终点；最值得做的是把诊断价值显式写入扫描策略。'},
  {sec:'Clinical Detection and Intervention',sub:'1.2 Response-based interactive diagnosis',title:'响应式交互诊断：刺激使隐匿状态可观测',kind:'loop',lead:'系统施加受控刺激，通过组织、关节或神经系统的响应生成诊断证据。',loop:['选择刺激位置/强度','施加机械/电磁/运动刺激','测量力学/MEP/EMG 响应','更新状态并选择下一刺激'],boundary:'边界：仅把工具移动到预定位置不够；反馈必须改变后续刺激、映射或停止。'},
  {sec:'Clinical Detection and Intervention',sub:'1.2 Response-based interactive diagnosis',title:'响应式交互诊断：已有工作与成熟度',kind:'landscape',lead:'机器人触诊构成主要集群；弹性、关节激发与神经映射虽小，但闭环定义更清晰。',items:[['机器人触诊','80','多为仿体/离体'],['刺激—响应映射','54','小样本人体验证'],['弹性/刚度测绘','≈15','严格闭环很少'],['关节激发检查','≈27','多为量化测量']],foot:'最关键的筛选问题：刺激响应是否用于决定下一测点/刺激参数，而非仅离线分析。'},
  {sec:'Clinical Detection and Intervention',sub:'1.2 Response-based interactive diagnosis',title:'方向一：多模态机器人触诊与弹性测绘',kind:'evidence',lead:'把“摸哪里、压多深、何时换扫描模式”转化为序贯决策。',loop:['稀疏触诊','硬度后验图','Bayesian 选点','中心定位 → 边界滑扫'],metrics:[['双模态触觉层析 2025','肿瘤仿体','≤30 次定位；F1 >0.976'],['边界分割','滑动 B-scan','precision 0.983；面积误差 <0.25 mm²']],hardware:'小型化探头 · OCT/触觉传感 · 力/形变估计 · 序贯优化',gap:'证据仍为仿体：组织滑移、曲面、呼吸运动、疼痛阈值和真实病理差异是临床转化门槛。'},
  {sec:'Clinical Detection and Intervention',sub:'1.2 Response-based interactive diagnosis',title:'方向二：神经刺激—响应的主动映射',kind:'evidence',lead:'MEP/EMG 不是被动输出，而是选择下一个刺激位点的反馈信号。',loop:['机器人定位 TMS','刺激','记录 MEP/阈值','主动学习选下一点'],metrics:[['自动 hotspot hunting','8 名受试者','跨会话 CoG 偏移 1.4 mm'],['对照','网格 MEP / 手动搜索','7.0 / 9.6 mm'],['GP 主动学习','真实数据评估','自动采样≈或优于专家引导']],hardware:'机器人线圈定位 · 头部追踪 · EMG/MEP · 安全刺激边界',gap:'近期可做：前瞻性机器人集成 + 少脉冲可靠映射；必须把刺激安全、异常响应和人工中断置于控制环内。'},
  {sec:'Clinical Detection and Intervention',sub:'1.3 Sample-based interactive diagnosis',title:'采样式交互诊断：动作产生离体证据',kind:'loop',lead:'定位只是开始；真正的闭环需要让样本质量或检测结果决定复采、改靶或停止。',loop:['定位目标与安全路径','穿刺/抽吸/切取/采血','样本充分性或分析结果','复采 · 改靶 · 停止 · 升级'],boundary:'边界：单次成功进针 ≠ 诊断闭环；治疗性注射、消融和引流通常不属于本类。'},
  {sec:'Clinical Detection and Intervention',sub:'1.3 Sample-based interactive diagnosis',title:'采样式交互诊断：平台成熟不等于闭环成熟',kind:'landscape',lead:'采血和拭子具有人体验证；活检导航研究多，但“充分性反馈”仍是共同薄弱环节。',items:[['经皮/芯针活检','≈100','导航成熟；充分性弱'],['机器人采血','29','临床证据较强'],['机器人拭子','25','小规模临床'],['胶囊取样','≈62','装置/平台为主']],foot:'同一平台可多标签：支气管镜导航属于主动观察；到位后取样属于采样交互。'},
  {sec:'Clinical Detection and Intervention',sub:'1.3 Sample-based interactive diagnosis',title:'方向一：样本充分性感知的机器人活检',kind:'evidence',lead:'把 adequacy gate 放进机器人控制环：不是“取到了”，而是“足够回答临床问题了吗？”',loop:['影像定位','取样','快速充分性/组织判别','不足→改靶/增采；充分→停止'],metrics:[['TARGET 2025','679 例 / 21 中心','严格诊断产率 61.6%'],['恶性敏感度','12 个月判定','78.8%'],['结论','大型临床导航/取样证据','尚非病理驱动自主复采']],hardware:'机器人支气管镜/穿刺平台 · 定位影像 · 快速细胞学/光谱/阻抗 · 样本追踪',gap:'优先研究：实时或近实时充分性代理、采样点多样性、止血/风险约束与可解释停止规则。'},
  {sec:'Clinical Detection and Intervention',sub:'1.3 Sample-based interactive diagnosis',title:'方向二：闭环采血与感染性标本采集',kind:'compare',lead:'两个近期可转化场景：静脉通路可多模态确认；拭子可用力与位姿反馈标准化。',cols:[['机器人采血｜ADOPT 2026','153 例等效性 + 1,633 例常规使用','适宜血管中首针成功 94.5%','NIR + 超声 + Doppler','优势：明确临床工作流与样本质量'],['自主拭子｜SR-NOCS','52 名临床参与者','与人工采样报告完全阳性相关','力敏机器人 + 阻抗控制','局限：规模小、效率与适应人群待验证']],gap:'共同终点：成功率之外，还应报告样本充分性、疼痛、耗时、失败恢复和工作人员介入。'},
  {sec:'Laboratory Diagnostics and Assay Development',sub:'2.0 Meaning and loop',title:'实验室诊断：结果驱动的物理检测工作流',kind:'loop',lead:'当结果改变下一次分流、复检、反应条件或实验选择时，实验室自动化才具有诊断闭环。',loop:['样本/质控状态','选择检测或实验','物理执行与测量','结果→分流/复检/调参/停止'],boundary:'固定流水线属于自动化基础；跨仪器协调、异常恢复和结果驱动的协议优化才是关键具身能力。'},
  {sec:'Laboratory Diagnostics and Assay Development',sub:'2.1 Result-driven workflows',title:'任务一：智能反射检测与异常恢复',kind:'roadmap',lead:'将“异常结果后怎么办”编码为可审计、可回退的物理工作流。',stages:[['触发','初检异常 / 质控失败 / 样本不足','结构化状态'],['决策','复测 / 稀释 / 追加项目 / 转人工','规则 + 学习模型'],['执行与验证','跨仪器调度 / 结果一致性检查','闭环日志']],resources:[['数据','LIS 事件日志、样本轨迹、质控与人工纠错'],['硬件','条码与分拣、自动移液、分析仪接口、缓存位'],['安全','限定规则域；矛盾结果 abstain；人工备用流程']],gap:'机器学习“建议反射检测”不等于已部署闭环；需要前瞻性验证工作量、漏检、延迟与异常恢复。'},
  {sec:'Laboratory Diagnostics and Assay Development',sub:'2.2 Programmable microfluidics',title:'任务二：可编程微流控与样本分流',kind:'evidence',lead:'在液滴尺度执行移动、合并、分裂与反应，使检测协议能够根据中间结果重构。',loop:['液滴视觉状态','选择路由/合并/分裂','电磁或数字微流控执行','反应读出更新方案'],metrics:[['Ferrobotic swarms 2022','PCB 线圈阵列 + RT-LAMP','展示患病率自适应 pooling'],['图像反馈 DMF 2023','相机实时定位液滴','支持自动 IVD 控制'],['证据边界','器件/临床样本演示','尚非日常检验科部署']],hardware:'低成本 PCB 阵列 / DMF 芯片 · 相机 · 温控与荧光读出 · 污染控制',gap:'最有价值的医学任务：样本稀缺时的分流、阳性后反射检测、失败反应的在线恢复。'},
  {sec:'Laboratory Diagnostics and Assay Development',sub:'2.3 Self-driving assay development',title:'任务三：自驱动检测与分析方法开发',kind:'loop',lead:'目标—实验—测量—学习—下一实验：把试剂和仪器当作主动获取证据的身体。',loop:['定义性能目标','选择下一实验','机器人执行 + QC','模型更新并停止/继续'],boundary:'SAMPLE 等平台证明架构可行；迁移到临床检测需加入基质效应、批间差、可追溯性和临床效用终点。'},
  {sec:'Laboratory Diagnostics and Assay Development',sub:'2.4 Prioritization',title:'实验室方向优先级：从固定自动化到价值驱动闭环',kind:'priority',lead:'近期优先选择可在现有实验室硬件上验证、且反馈价值明确的任务。',items:[['智能反射 + 异常恢复','高临床价值','高可实施性','先做'],['可编程样本分流/DMF','中高价值','中等硬件门槛','联合做'],['自驱动 assay 开发','长期平台价值','高验证门槛','布局']],foot:'推荐指标：turnaround time、无效复检、样本浪费、人员介入、恢复成功率、最终决策改变。'},
  {sec:'Everyday Embodied Monitoring and Adaptive Support',sub:'3.0 Meaning and loop',title:'日常具身监测：从连续感知到主动确认',kind:'loop',lead:'连续感知只有在异常能触发新的测量、询问、设备调整或升级时，才接近具身诊断。',loop:['家庭/可穿戴连续感知','个体状态与不确定性','主动确认/改变采样','新证据→继续监测或升级'],boundary:'静态风险评分与报警仍是支撑技术；行动多由患者或临床人员执行，应如实标注人类角色。'},
  {sec:'Everyday Embodied Monitoring and Adaptive Support',sub:'3.1 Evidence landscape',title:'日常监测：已有证据与闭环缺口',kind:'trajectories',lead:'大规模纵向研究证明“可感知”，但大多数闭环仍停在通知与人工确认。',items:[['Apple Heart','419,297 人','0.52% 收到通知','通知→远程问诊→邮寄 ECG'],['夜间呼吸识别 PD','7,671 人','AUC 0.90 / 外部 0.85','强监测；无自适应行动'],['智能表症状前 COVID','个体基线','异常可先于症状','回顾性状态估计']],foot:'成熟度不能只看样本量：关键是异常后是否获得可验证的新证据，以及行动由谁承担。'},
  {sec:'Everyday Embodied Monitoring and Adaptive Support',sub:'3.2 Personal baselines',title:'方向一：个体基线驱动的动态状态估计',kind:'trajectory',lead:'先问“与这个人的正常状态相比发生了什么”，再问“与群体阈值相比是否异常”。',stages:[['个人基线','多周稳定窗口','心率/睡眠/呼吸/活动'],['偏离检测','区分疾病、行为、治疗与传感漂移','动态 latent state'],['选择新证据','提高频率、换模态、主动询问','within-person calibration']],resources:[['数据条件','长期连续、时间同步、情境标签与缺失原因'],['验证','前瞻性个体校准；提前量与误报负担'],['风险','弱势群体的数据贫困、设备适配与连接成本']],gap:'“digital twin”仅用于能持续更新、绑定具体患者并证明决策价值的模型。'},
  {sec:'Everyday Embodied Monitoring and Adaptive Support',sub:'3.3 Active confirmation',title:'方向二：异常后的主动确认',kind:'roadmap',lead:'把单次警报变成最小负担的确认序列，而不是持续增加传感器。',stages:[['Detect','偏离个人基线','不确定异常'],['Confirm','提高采样频率 / 第二模态 / 主动问询','证据一致性'],['Escalate or recover','远程医疗 / 到院检查 / 返回基线','有界升级']],resources:[['可用场景','心律失常、感染、跌倒后状态、呼吸恶化'],['优化目标','预期临床价值 − 误报 − 用户负担 − 延迟'],['人类角色','患者可暂停/拒绝；临床人员处理矛盾或高风险结果']],gap:'Apple Heart 提供 detect→confirm 的真实工作流锚点，但动作主要由人和医疗服务完成。'},
  {sec:'Everyday Embodied Monitoring and Adaptive Support',sub:'3.4 Adaptive support ecosystem',title:'方向三：检测—自适应支持生态',kind:'loop',lead:'检测、支持和复评连接后，任何局部错误都可能被闭环放大。',loop:['检测变化','估计风险与可逆性','有界支持/设备调整','复评疗效与副作用'],boundary:'设计底线：bounded actions、safe degraded state、human override、延迟/缺失/矛盾反馈恢复。'},
  {sec:'Cross-domain synthesis',sub:'4.1 Comparison',title:'跨领域比较：闭环价值取决于减少关键不确定性',kind:'matrix',lead:'同一闭环框架下，动作不可逆性、反馈延迟和证据成熟度决定治理强度。',items:[['主动观察','低—中','秒级','人体可行性较强'],['响应交互','中','毫秒—分钟','多为原型/小样本'],['采样交互','中—高','分钟—天','采血成熟；充分性缺口'],['实验室','低—中','分钟—小时','器件闭环强；部署弱'],['日常监测','低','小时—月','纵向数据强；动作环弱']],foot:'列：机制｜行动风险｜反馈延迟｜当前证据。成熟度不是自治等级。'},
  {sec:'Research opportunities',sub:'4.2 Recommended entry points',title:'优先研究切入点',kind:'priority',lead:'优先做“闭环可验证、硬件可获得、临床问题清楚”的研究，而不是追求最大自治。',items:[['① 主动光学/光谱扫描','信息增益与停止规则可离线+仿体验证','低侵入；数据与硬件可控','首选'],['② 样本充分性感知活检','临床痛点明确；闭环缺口大','需跨病理合作与高安全门槛','高价值'],['③ 家庭异常后主动确认','可先做软件+现有可穿戴','需长期前瞻性与依从性设计','可并行']],foot:'机器人超声适合作为成熟参照和算法验证平台，但硬件/临床竞争更强。'},
  {sec:'Research roadmap',sub:'4.3 Translation path',title:'三阶段研究路线',kind:'roadmap',lead:'每一阶段都用可证伪的闭环终点推进，而非直接从模拟跳到“临床自主”。',stages:[['0–12 个月','回放/仿体闭环','信息增益、失败恢复、停止校准'],['12–24 个月','受控人体可行性','安全、可重复性、人员介入、负担'],['24–48 个月','前瞻性工作流试验','决策时间、无效检测、诊断遗漏、患者结局']],resources:[['Gate 1','证明反馈优于固定策略'],['Gate 2','限定运行域内安全可靠'],['Gate 3','证明改变患者相关决策']],gap:'全过程保留日志、人工接管与回滚；证据强度随行动不可逆性同步提高。'},
  {sec:'Take-home message',sub:'5.0 Conclusion',title:'结论：从被动检测到适应性证据获取',kind:'conclusion',lead:'Embodied diagnostics 的单位不是传感器、模型或机器人，而是能改变下一次证据获取的 sensing–decision–action–feedback loop。',items:[['已有能力','机器人超声/采血、可编程实验室和纵向监测展示了部分闭环'],['核心缺口','样本充分性、跨仪器异常恢复、异常后主动确认与临床效用验证'],['成功标准','反馈是否更及时、安全、公平地减少 consequential uncertainty']],foot:'目标不是“更自主”，而是“用更少代价获得足以支持决策的下一份证据”。'},
  null
];

function addText(s,text,pos,size=20,color=INK,bold=false,align='left',fill='none'){
 const x=s.shapes.add({geometry:'textbox',position:pos,fill,line:{style:'solid',fill:'none',width:0}}); x.text=text;
 x.text.style={fontSize:size,bold,color,alignment:align,verticalAlignment:'middle',autoFit:'shrinkText',wrap:'square',typeface:bodyFont,insets:{top:3,right:5,bottom:3,left:5}}; return x;
}
function box(s,pos,fill='#FFFFFF',line=GRID,r=14){return s.shapes.add({geometry:'roundRect',position:pos,fill,line:{style:'solid',fill:line,width:1},borderRadius:r});}
function pill(s,text,x,y,w,color=P){const b=box(s,{left:x,top:y,width:w,height:28},color,color,14); addText(s,text,{left:x,top:y,width:w,height:28},14,'#FFFFFF',true,'center'); return b;}
function lead(s,t){addText(s,t,{left:34,top:122,width:1160,height:40},20,P,true);}
function loop(s,arr,y=185){const x0=58,w=248,g=38; const nodes=[]; for(let i=0;i<arr.length;i++){nodes.push(box(s,{left:x0+i*(w+g),top:y,width:w,height:92},i===1?L2:'#FFFFFF',i===1?P2:GRID,16));}
 for(let i=0;i<nodes.length-1;i++)s.shapes.connect(nodes[i],nodes[i+1],{kind:'straight',fromSide:'right',toSide:'left',line:{style:'solid',fill:P2,width:2},head:{type:'triangle',width:'sm',length:'sm'}});
 arr.forEach((t,i)=>addText(s,`${i+1}\n${t}`,{left:x0+i*(w+g)+10,top:y+9,width:w-20,height:74},20,i===1?P:INK,true,'center'));
 const ret=s.shapes.add({geometry:'line',position:{left:x0+w/2,top:y+112,width:3*(w+g),height:0},fill:'none',line:{style:'dash',fill:P2,width:2}}); ret.sendToBack();
}
function note(s,urls=[]){s.speakerNotes.textFrame.setText(`[Sources]\n${urls.join('\n')}\n[/Sources]`);s.speakerNotes.setVisible(true);}
function metricRows(s,rows,y=330){rows.forEach((r,i)=>{const yy=y+i*72; box(s,{left:42,top:yy,width:1144,height:58},i%2?L:'#FFFFFF',i%2?L2:GRID,12); addText(s,r[0],{left:60,top:yy+4,width:260,height:50},18,P,true); addText(s,r[1],{left:330,top:yy+4,width:510,height:50},18,INK,false); addText(s,r[2],{left:850,top:yy+4,width:315,height:50},18,i===0?GREEN:P2,true,'right');});}
function footer(s,t){addText(s,t,{left:42,top:604,width:1135,height:46},16,MUTED,false);}
function landscape(s,d){lead(s,d.lead); const max=Math.max(...d.items.map(x=>Number(String(x[1]).replace(/[^0-9.]/g,''))||1)); d.items.forEach((r,i)=>{const y=176+i*91; addText(s,r[0],{left:45,top:y,width:235,height:34},18,INK,true); const v=Number(String(r[1]).replace(/[^0-9.]/g,''))||25; box(s,{left:288,top:y+4,width:650,height:28},'#EEE9F0','#EEE9F0',14); box(s,{left:288,top:y+4,width:Math.max(44,650*v/max),height:28},i===0?P:P2,i===0?P:P2,14); addText(s,r[1],{left:953,top:y,width:85,height:34},20,P,true,'right'); pill(s,r[2],1048,y,135,i===0?GREEN:P2);}); footer(s,d.foot);}
function evidence(s,d){lead(s,d.lead); loop(s,d.loop,165); metricRows(s,d.metrics,304); pill(s,'硬件 / 数据条件',42,535,150); addText(s,d.hardware,{left:204,top:530,width:978,height:38},17,INK,false); footer(s,d.gap);}
function loopSlide(s,d){lead(s,d.lead); loop(s,d.loop,210); box(s,{left:98,top:420,width:1084,height:106},L,P2,18); addText(s,d.boundary,{left:125,top:436,width:1030,height:74},20,P,true,'center'); addText(s,'反馈必须改变下一动作', {left:430,top:565,width:420,height:40},21,RED,true,'center');}
function roadmap(s,d){lead(s,d.lead); const x=[48,434,820]; const ns=[]; d.stages.forEach((r,i)=>{ns.push(box(s,{left:x[i],top:170,width:350,height:155},i===1?L:'#FFFFFF',i===1?P2:GRID,18)); addText(s,r[0],{left:x[i]+20,top:184,width:310,height:32},21,P,true,'center'); addText(s,r[1],{left:x[i]+20,top:224,width:310,height:42},19,INK,true,'center'); addText(s,r[2],{left:x[i]+20,top:272,width:310,height:36},16,MUTED,false,'center');}); for(let i=0;i<2;i++)s.shapes.connect(ns[i],ns[i+1],{kind:'straight',fromSide:'right',toSide:'left',line:{style:'solid',fill:P2,width:2},head:{type:'triangle',width:'sm',length:'sm'}}); d.resources.forEach((r,i)=>{const y=360+i*58; pill(s,r[0],52,y,110,i===0?P:BLUE); addText(s,r[1],{left:176,top:y-2,width:995,height:34},17,INK,false);}); footer(s,d.gap);}
function compare(s,d){lead(s,d.lead); d.cols.forEach((c,i)=>{const x=50+i*585; box(s,{left:x,top:170,width:545,height:350},i===0?L:'#FFFFFF',i===0?P2:GRID,20); addText(s,c[0],{left:x+25,top:190,width:495,height:45},22,P,true,'center'); c.slice(1).forEach((t,j)=>{pill(s,String(j+1),x+30,255+j*57,35,j===1?GREEN:P2); addText(s,t,{left:x+82,top:249+j*57,width:425,height:42},18,j===1?GREEN:INK,j===1);});}); footer(s,d.gap);}
function priority(s,d){lead(s,d.lead); d.items.forEach((r,i)=>{const y=174+i*125; pill(s,r[3]||String(i+1),48,y,95,i===0?GREEN:P2); addText(s,r[0],{left:164,top:y-5,width:340,height:45},21,P,true); addText(s,r[1],{left:500,top:y-5,width:350,height:48},17,INK,false); addText(s,r[2],{left:870,top:y-5,width:300,height:48},17,MUTED,false); box(s,{left:164,top:y+56,width:1006,height:8},i===0?P:(i===1?P2:GRID),i===0?P:(i===1?P2:GRID),4);}); footer(s,d.foot);}
function trajectories(s,d){lead(s,d.lead); const colors=[P,BLUE,GREEN]; d.items.forEach((r,i)=>{const y=175+i*126; box(s,{left:52,top:y,width:1122,height:99},i===0?L:'#FFFFFF',i===0?P2:GRID,18); pill(s,r[0],70,y+18,205,colors[i]); addText(s,r[1],{left:300,top:y+10,width:190,height:40},23,P,true,'center'); addText(s,r[2],{left:500,top:y+10,width:240,height:40},18,INK,true,'center'); addText(s,r[3],{left:755,top:y+10,width:390,height:72},17,MUTED,false);}); footer(s,d.foot);}
function matrix(s,d){lead(s,d.lead); const heads=['机制','行动风险','反馈延迟','证据成熟度']; const widths=[250,220,220,430], xs=[42,292,512,732]; heads.forEach((h,i)=>{box(s,{left:xs[i],top:160,width:widths[i],height:48},P,P,0);addText(s,h,{left:xs[i],top:160,width:widths[i],height:48},18,'#FFFFFF',true,'center');}); d.items.forEach((r,ri)=>r.forEach((v,i)=>{const y=208+ri*68;box(s,{left:xs[i],top:y,width:widths[i],height:68},ri%2?L:'#FFFFFF',GRID,0);addText(s,v,{left:xs[i]+6,top:y+5,width:widths[i]-12,height:58},17,i===0?P:INK,i===0,'center');})); footer(s,d.foot);}
function conclusion(s,d){lead(s,d.lead); d.items.forEach((r,i)=>{const x=54+i*382; box(s,{left:x,top:220,width:350,height:235},i===1?L:'#FFFFFF',i===1?P2:GRID,20); pill(s,r[0],x+58,246,234,i===1?P:GREEN); addText(s,r[1],{left:x+28,top:300,width:294,height:120},19,INK,true,'center');}); box(s,{left:180,top:520,width:920,height:72},P,P,18);addText(s,d.foot,{left:205,top:530,width:870,height:52},22,'#FFFFFF',true,'center');}

for(let idx=4;idx<29;idx++){
 const s=deck.slides.getItem(idx),d=slides[idx]; const page=idx+1;
 const headerSec=d.sec==='Laboratory Diagnostics and Assay Development'?'Laboratory Diagnostics & Assay':d.sec==='Everyday Embodied Monitoring and Adaptive Support'?'Everyday Monitoring & Adaptive Support':d.sec;
 for(const sh of s.shapes.items){if(sh.name==='文本框 4')sh.text=headerSec;if(sh.name==='文本框 9')sh.text=d.sub;if(sh.name==='文本框 7')sh.text=String(page);}
 addText(s,d.title,{left:32,top:78,width:1150,height:42},28,INK,true);
 if(d.kind==='landscape')landscape(s,d); else if(d.kind==='evidence')evidence(s,d); else if(d.kind==='loop')loopSlide(s,d); else if(d.kind==='roadmap'||d.kind==='trajectory')roadmap(s,d); else if(d.kind==='compare')compare(s,d); else if(d.kind==='priority')priority(s,d); else if(d.kind==='trajectories')trajectories(s,d); else if(d.kind==='matrix')matrix(s,d); else if(d.kind==='conclusion')conclusion(s,d);
 const sources={5:['repo:data/literature_task_assignments_all_snapshots.csv'],6:['https://doi.org/10.1038/s41467-024-48421-y','https://doi.org/10.1038/s41467-025-62865-w'],7:['repo:data/bibliometrics'],9:['repo:data/literature_task_assignments_all_snapshots.csv'],10:['https://doi.org/10.34133/cbsystems.0348'],11:['https://doi.org/10.1016/j.neuroimage.2015.09.013','https://doi.org/10.1109/TNSRE.2021.3105696'],13:['repo:data/literature_task_assignments_all_snapshots.csv'],14:['https://doi.org/10.1016/j.chest.2025.04.022'],15:['https://doi.org/10.1093/clinchem/hvag029','https://pubmed.ncbi.nlm.nih.gov/38167977/'],17:['https://pubmed.ncbi.nlm.nih.gov/37812770/'],18:['https://doi.org/10.1038/s41586-022-05408-3','https://pubmed.ncbi.nlm.nih.gov/37476053/'],19:['https://doi.org/10.1038/s44286-023-00002-4'],22:['https://doi.org/10.1056/NEJMoa1901183','https://doi.org/10.1038/s41591-022-01932-x','https://doi.org/10.1038/s41551-020-00640-6'],23:['https://doi.org/10.1038/s41551-020-00640-6','https://doi.org/10.1038/s41591-022-01932-x'],24:['https://doi.org/10.1056/NEJMoa1901183']}[page]||[]; note(s,sources);
}
for(const sh of deck.slides.getItem(29).shapes.items){
 if(sh.name==='文本框 7')sh.text='30';
 if(String(sh.text?.toString?.()||'').includes('Presenter:'))sh.text='Presenter: Wanran Sun  ·  2026.08';
}
await fs.mkdir(path.dirname(OUT),{recursive:true});
for(let i=0;i<deck.slides.items.length;i++){const s=deck.slides.getItem(i);const png=await deck.export({slide:s,format:'png',scale:1});await fs.writeFile(`final-slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await png.arrayBuffer())); const lay=await s.export({format:'layout'});await fs.writeFile(`final-slide-${String(i+1).padStart(2,'0')}.layout.json`,await lay.text());}
const pptx=await PresentationFile.exportPptx(deck);await pptx.save(OUT);console.log(OUT);
